### Vars
@baseUrl = http://localhost:3000/api

### 1. New user registration
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Super User",
  "email": "test@example.com",
  "password": "password123"
}

### 2. Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### 3. User auth test
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiaWF0IjoxNzY5NzUyMjYxLCJleHAiOjE3Njk4Mzg2NjF9.2TDkZS7VYTe8EK48lPF6MYJ3H7LFslwFm-7GBlTwV3E